steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/zeta-ascent-272907/a2sv:$SHORT_SHA", "."]
    dir: "Backend"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/zeta-ascent-272907/a2sv:$SHORT_SHA"]
    dir: "Backend"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "a2sv-api",
        "--region=us-central1",
        "--platform=managed",
        "--image=gcr.io/zeta-ascent-272907/a2sv:$SHORT_SHA",
      ]
