import LocalizedStrings from "react-native-localization";

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let strings = new LocalizedStrings({
  "en-US": {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
  },
  en: {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
  },
  am: {
    Information: "መረጃ",
    Data: "ትንታኔ",
    Map: "ካርታ",
    Symptoms: "የኔ ምልክቶች",
    Home: "መነሻ ገፅ",
    News: "ዜና",
    Ethiopia: "ኢትዮጵያ",
    About: "ስለ መተግበሪያው ባለቤቶች",
    Settings: "ማስተካከያ",
    EditProfile: "መረጃዬን አስተካክል",
    ChangePassword: "የሚስጥር ቁልፍ ማስተካከያ",
    TermsAndPrivacy: "ውሎች እና ግላዊነት",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "ውጣ",
    Search: "ይፈልጉ..",
    Welcome: "እንኳን ደህና መጡ",
    Username: "የተጠቃሚ ስም",
    Password: "የሚስጥር ቁልፍ",
    SignIn: "ግባ",
    SignUp: "ይመዝገቡ",
    AgeGroup: "እድሜ ክልል",
    Male: "ወንድ",
    Female: "ሴት",
    Gender: "ፃታ",
    ConfirmPassword: "የሚስጥር ቁልፎን ያረጋግጡ",
    ReadMore: "ገብተው ያንብቡ",
    WhatIsCOVID19: "COVID-19 ምንድነው?",
    COVID19Symptoms: "ምልክቶች",
    Prevention: "መከላከያ መንገዶች",
    HowDoesItSpreads: "እንዴት ይተላለፋል ?",
    MessageFromUs: "የኛ መልዕክቶች",
  },
});
