import LocalizedStrings from "react-native-localization";

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

export let strings = new LocalizedStrings({
  "en-US": {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
    Refresh: "Refresh",
    DailyStats: "Daily Stats",
    TotalStats: "Total Stats",
    DailyStatsGraph: "Daily Stats Graph",
    TotalStatsGraph: "Total Stats Graph",
    DailyRatesGraph: "Daily Rates Graph",
    NewConfirmed: "New Confirmed",
    NewRecovered: "New Recovered",
    NewDeath: "New Death",
    TotalConfirmed: "Total Confirmed",
    TotalRecovered: "Total Recovered",
    TotalDeath: "Total Death",
    StartDate: "Start Date",
    EndDate: "End Date",
    Confirmed: "Confirmed",
    Recovered: "Recovered",
    Death: "Death",
    Deaths: "Deaths",
    TestCounts: "Test Counts",
    ConfirmedRate: "Confirmed Rate",
    RecoveryRate: "Recovery Rate",
    DeathRate: "Death Rate",
    Heat: "HEAT",
    Regional: "REGIONAL",
    SearchCity: "Search City",
    GEO: "GEO",
    GeneralInfo: "General Info",
    DemoGraphics: "Demo Graphics",
    Close: "Close",
    TopNews: "Top News",
    GoToNews: "GO TO NEWS",
    NewsDetail: "News Detail",
    AboutUs: "About Us",
    TrackSYM: "TRACK SYM",
    WhoWeAre: "WHO WE ARE",
    YourData: "YOUR DATA",
    CheckOutOurWebsite: "CHECK OUT OUR WESITE",
    SignInToYourAccount: "Sign In To Your Accout",
    DoNotHaveAccount: "Don't have account? Sign up",
    CovidDetail: "COVID DETAIL",
    CoronaVirusDesease2019: "CORONAVIRUS DESEASE 2019",
    WhatDoWeKnowSoFar: "WHAT DO WE KNOW SO FAR ?",
    WhereDidItComeFrom: "WHERE DID IT COME FROM ?",
    Misconceptions: "MISCONCEPTIONS",
    SymptomsOfCOVID19: "SYMPTOMS of COVID-19",
    MostCommon: "MOST COMMON",
    HighFever: "High Fever",
    DryCough: "Dry Cough",
    Fatigue: "Fatigue",
    ShortnessOfBreath: "Shortness of Breath",
    Myalgia: "Myalgia",
    LessCommon: "LESS COMMON",
    Headache: "HeadAche",
    SoreThroat: "Sore Throat",
    Chills: "Chills",
    Anosmia: "Anosmia",
    PreventionIsBetterThanCure: "PREVENTION IS BETTER THAN CURE!",
    HandWashing: "Hand Washing",
    SocialDistancing: "Social Distancing",
    RecommendedMethods: "RECOMMENDED METHODS",
    RespiratoryHygiene: "Respiratory Hygiene",
    StayInformed: "Stay Informed",
    Spread: "SPREAD",
    HowDoesCoronavirusBecomeContagious:
      "How does coronavirus become contagious ?",
    MessageFromTrackSym: "Message From TrackSym",
    MajorConcern: "MAJOR CONCERN",
    MySymptoms: "My Symptoms",
    EditYourSymptoms: "Edit Your Symptoms",
    LoadingYourSymptom: "Loading your symptom",
    YouHaveNotRegisteredAnySymptom: "You have not registered any symptom",
    RunnyNose: "Runny Nose",
    Sneezing: "Sneezing",
    Conjunctivitis: "Conjunctivitis",
    Diarrhea: "Diarrhea",
    MediumGradeFever: "Medium-grade fever",
    HighGradeFever: "High-grade fever",
    PersistentDryCough: "Persistent Dry Cough",
    DifficultyBreathing: "Difficulty Breathing",
    Pneumonia: "Pneumonia",
    RepeatedShakingWithChills: "Repeated Shaking with Chills",
    ChangeProfile: "CHANGE PROFILE",
    UpdateYourAgeGroup: "Update your age group",
    UpdateYourGender: "Update your gender",
    NewPassword: "NEW PASSWORD",
    PrivacyPolicy: "Privacy Policy",
    InformationCollectionAndUse: "Information Collection and Use",
    ServiceProviders: "Service Providers",
    LogData: "Log Data",
    Security: "Security",
    LinkToOtherSites: "Link to Other Sites",
    ChildrensPrivacy: "Children’s Privacy",
    ChangesToThisPrivacyPolicy: "Changes to This Privacy Policy",
    TermsAndConditions: "Terms & Conditions",
    ChangesToThisTermsAndConditions: "Terms to This Terms and Conditions",
    ComingSoon: "Coming Soon!!",
    Heat: "Heat",
    Regional: "Regional",
    SaveChanges: "Save Changes",
    Done: "Done",
    PleaseTryAgain: "Please try again!",
    YouHaveEnteredWrongUsernameOrPasswordPleaseTryAgain:
      "You have entered wrong username or password, Please try again",
    SigninValidationText:
      "You have entered wrong username or password, Please try again",
    Dismiss: "Dismiss",
    UsernameAlreadyExists: "Username already exists!",
    PrivacyPolicyShortText:
      "By creating an account, I agree to the Track Sym Terms of Use and Privacy Policy",
    PassWordIsRequired: "Password is required",
    PasswordDoesNotMatch: "Password doesn't match",
    PleaseEnterYourUsername: "Please enter your username!",
    UsernameIsRequired: "User name is required",
    PleaseEnterYourPassword: "Please enter your password!",
    PasswordDoNotMatch: "Password Don't match",
    WrongCurrentPassword: "Wrong current password!",
    Required: "required",
    CurrentPassword: "CURRENT PASSWORD",
    ConfirmNewPassword: "CONFIRM NEW PASSWORD",
    ConfirmNewPassword: "Confirm New Password",
    YouHaveSuccessfullyChangedYourPassword:
      "You have successfully changed your password",
    YouHaveSuccessfullyChangedYourProfile:
      "You have successfully changed your profile",
    Default: "Default",
    PasswordCanNotBeEmpty: "Password cannot be empty",
    Cancel: "CANCEL",
    Ok: "OK",
    ConnectionProblem: "Connection Problem",
    CouldNotConnectToServer: "Couldn't connect to server",
    PleaseCheckYourConnection:
      "Please check your internet connection and try again!",
    AgreeingTermsAndServiceOnSignUp:
      "By creating an account, I agree to the Track Sym Terms of\nUse and Privacy Policy",
    CantConnectDueToConnection:
      "Oops, looks like we have connection problem, please try again!",
    PleaseSelectGender: "Please select your gender",
    PleaseSelectAgeGroup: "Please select your age group",
    LoadingGraphDescription: "Loading graph description",
    LoadingCriteriaDescription: "Loading criteria description",
    Languages: "Languages",
    English: "English",
    Amharic: "Amharic",
    Oromiffa: "Oromiffa",
    Turkish: "Turkish",
  },
  en: {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
    Refresh: "Refresh",
    DailyStats: "Daily Stats",
    TotalStats: "Total Stats",
    DailyStatsGraph: "Daily Stats Graph",
    TotalStatsGraph: "Total Stats Graph",
    DailyRatesGraph: "Daily Rates Graph",
    NewConfirmed: "New Confrimed",
    NewRecovered: "New Recovered",
    NewDeath: "New Death",
    TotalConfirmed: "Total Confrimed",
    TotalRecovered: "Total Recovered",
    TotalDeath: "Total Death",
    StartDate: "Start Date",
    EndDate: "End Date",
    Confirmed: "Confrimed",
    Recovered: "Recovered",
    Death: "Death",
    Deaths: "Deaths",
    TestCounts: "Test Counts",
    ConfirmedRate: "Confirmed Rate",
    RecoveryRate: "Recovery Rate",
    DeathRate: "Death Rate",
    Heat: "HEAT",
    Regional: "REGIONAL",
    SearchCity: "Search City",
    GEO: "GEO",
    GeneralInfo: "General Info",
    DemoGraphics: "Demo Graphics",
    Close: "Close",
    TopNews: "Top News",
    GoToNews: "GO TO NEWS",
    NewsDetail: "News Detail",
    AboutUs: "About Us",
    TrackSYM: "TRACK SYM",
    WhoWeAre: "WHO WE ARE",
    YourData: "YOUR DATA",
    CheckOutOurWebsite: "CHECK OUT OUR WESITE",
    SignInToYourAccount: "Sign In To Your Accout",
    DoNotHaveAccount: "Don't have account? Sign up",
    CovidDetail: "COVID DETAIL",
    CoronaVirusDesease2019: "CORONAVIRUS DESEASE 2019",
    WhatDoWeKnowSoFar: "WHAT DO WE KNOW SO FAR ?",
    WhereDidItComeFrom: "WHERE DID IT COME FROM ?",
    Misconceptions: "MISCONCEPTIONS",
    SymptomsOfCOVID19: "SYMPTOMS of COVID-19",
    MostCommon: "MOST COMMON",
    HighFever: "High Fever",
    DryCough: "Dry Cough",
    Fatigue: "Fatigue",
    ShortnessOfBreath: "Shortness of Breath",
    Myalgia: "Myalgia",
    LessCommon: "LESS COMMON",
    Headache: "HeadAche",
    SoreThroat: "Sore Throat",
    Chills: "Chills",
    Anosmia: "Anosmia",
    PreventionIsBetterThanCure: "PREVENTION IS BETTER THAN CURE!",
    HandWashing: "Hand Washing",
    SocialDistancing: "Social Distancing",
    RecommendedMethods: "RECOMMENDED METHODS",
    RespiratoryHygiene: "Respiratory Hygiene",
    StayInformed: "Stay Informed",
    Spread: "SPREAD",
    HowDoesCoronavirusBecomeContagious:
      "How does coronavirus become contagious ?",
    MessageFromTrackSym: "Message From TrackSym",
    MajorConcern: "MAJOR CONCERN",
    MySymptoms: "My Symptoms",
    EditYourSymptoms: "Edit Your Symptoms",
    LoadingYourSymptom: "Loading your symptom",
    YouHaveNotRegisteredAnySymptom: "You have not registered any symptom",
    RunnyNose: "Runny Nose",
    Sneezing: "Sneezing",
    Conjunctivitis: "Conjunctivitis",
    Diarrhea: "Diarrhea",
    MediumGradeFever: "Medium-grade fever",
    HighGradeFever: "High-grade fever",
    PersistentDryCough: "Persistent Dry Cough",
    DifficultyBreathing: "Difficulty Breathing",
    Pneumonia: "Pneumonia",
    RepeatedShakingWithChills: "Repeated Shaking with Chills",
    ChangeProfile: "CHANGE PROFILE",
    UpdateYourAgeGroup: "Update your age group",
    UpdateYourGender: "Update your gender",
    NewPassword: "NEW PASSWORD",
    PrivacyPolicy: "Privacy Policy",
    InformationCollectionAndUse: "Information Collection and Use",
    ServiceProviders: "Service Providers",
    LogData: "Log Data",
    Security: "Security",
    LinkToOtherSites: "Link to Other Sites",
    ChildrensPrivacy: "Children’s Privacy",
    ChangesToThisPrivacyPolicy: "Changes to This Privacy Policy",
    TermsAndConditions: "Terms & Conditions",
    ChangesToThisTermsAndConditions: "Terms to This Terms and Conditions",
    ComingSoon: "Coming Soon!!",
    Heat: "Heat",
    Regional: "Regional",
    SaveChanges: "Save Changes",
    Done: "Done",
    PleaseTryAgain: "Please try again!",
    YouHaveEnteredWrongUsernameOrPasswordPleaseTryAgain:
      "You have entered wrong username or password, Please try again",
    SigninValidationText:
      "You have entered wrong username or password, Please try again",
    Dismiss: "Dismiss",
    UsernameAlreadyExists: "Username already exists!",
    PrivacyPolicyShortText:
      "By creating an account, I agree to the Track Sym Terms of Use and Privacy Policy",
    PassWordIsRequired: "Password is required",
    PasswordDoesNotMatch: "Password doesn't match",
    PleaseEnterYourUsername: "Please enter your username!",
    UsernameIsRequired: "User name is required",
    PleaseEnterYourPassword: "Please enter your password!",
    PasswordDoNotMatch: "Password Don't match",
    WrongCurrentPassword: "Wrong current password!",
    Required: "required",
    CurrentPassword: "CURRENT PASSWORD",
    ConfirmNewPassword: "CONFIRM NEW PASSWORD",
    ConfirmNewPassword: "Confirm New Password",
    YouHaveSuccessfullyChangedYourPassword:
      "You have successfully changed your password",
    YouHaveSuccessfullyChangedYourProfile:
      "You have successfully changed your profile",
    Default: "Default",
    PasswordCanNotBeEmpty: "Password cannot be empty",
    Cancel: "CANCEL",
    Ok: "OK",
    ConnectionProblem: "Connection Problem",
    CouldNotConnectToServer: "Couldn't connect to server",
    PleaseCheckYourConnection: "Check your internet connection and try again!",
    AgreeingTermsAndServiceOnSignUp:
      "By creating an account, I agree to the Track Sym Terms of\nUse and Privacy Policy",
    CantConnectDueToConnection:
      "Oops, looks like we have connection problem, please try again!",
    PleaseSelectGender: "Please select your gender",
    PleaseSelectAgeGroup: "Please select your age group",
    LoadingGraphDescription: "Loading graph description",
    LoadingCriteriaDescription: "Loading criteria description",
    Languages: "Languages",
    English: "English",
    Amharic: "Amharic",
    Oromiffa: "Oromiffa",
    Turkish: "Turkish",
  },
  am: {
    Information: "መረጃ",
    Data: "ትንታኔ",
    Map: "ካርታ",
    Symptoms: "የኔ ምልክቶች",
    Home: "መነሻ ገፅ",
    News: "ዜና",
    Ethiopia: "ኢትዮጵያ",
    About: "ስለ መተግበሪያው ባለቤቶች",
    Settings: "ማስተካከያ",
    EditProfile: "መረጃዬን አስተካክል",
    ChangePassword: "የሚስጥር ቁልፍ ማስተካከያ",
    TermsAndPrivacy: "ውሎች እና ግላዊነት",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "ውጣ",
    Search: "ይፈልጉ..",
    Welcome: "እንኳን ደህና መጡ",
    Username: "የተጠቃሚ ስም",
    Password: "የሚስጥር ቁልፍ",
    SignIn: "ግባ",
    SignUp: "ይመዝገቡ",
    AgeGroup: "እድሜ ክልል",
    Male: "ወንድ",
    Female: "ሴት",
    Gender: "ፃታ",
    ConfirmPassword: "የሚስጥር ቁልፎን ያረጋግጡ",
    ReadMore: "ገብተው ያንብቡ",
    WhatIsCOVID19: "COVID-19 ምንድነው?",
    COVID19Symptoms: "ምልክቶች",
    Prevention: "መከላከያ መንገዶች",
    HowDoesItSpreads: "እንዴት ይተላለፋል ?",
    MessageFromUs: "የኛ መልዕክቶች",
    Refresh: "አድስ",
    DailyStats: "ዕለታዊ ስታቲስቲክስ",
    TotalStats: "ጠቅላላ ስታቲስቲክስ",
    DailyStatsGraph: "ዕለታዊ ስታቲስቲክስ ግራፍ",
    TotalStatsGraph: "ጠቅላላ ስታቲስቲክስ ግራፍ",
    DailyRatesGraph: "የቀኑ የለውጥ ደረጃ",
    NewConfirmed: "አዲስ የተረጋገጡ",
    NewRecovered: "አዲስ ያገገሙ",
    NewDeath: "አዲስ የሞቱ",
    TotalConfirmed: "ጠቅላላ የተረጋገጡ",
    TotalRecovered: "ጠቅላላ ያገገሙ",
    TotalDeath: "ጠቅላላ ሞት",
    StartDate: "የመጀመሪያ ቀን",
    EndDate: "የመጨረሻ ቀን",
    Confirmed: "የተረጋገጡ",
    Recovered: "ያገገሙ",
    Death: "የሞቱ",
    Deaths: "ሞት",
    TestCounts: "የምርመራ ብዛት",
    ConfirmedRate: "የተረጋገጡ የለውጥ ደረጃ",
    RecoveryRate: "ያገገሙ የለውጥ ደረጃ",
    DeathRate: "የሞቱ የለውጥ ደረጃ",
    Heat: "ሙቀት",
    Regional: "ክልላዊ",
    SearchCity: "ከተማ ፈልግ",
    GEO: "GEO",
    GeneralInfo: "አጠቃላይ መረጃ",
    DemoGraphics: "ዴሞግራፊክስ/ሥነ-ሕዝብ/",
    Close: "ዝጋ",
    TopNews: "ዋና ዋና ዜና",
    GoToNews: "ወደ ዜና ሂድ",
    NewsDetail: "የዜናው ዝርዝር",
    AboutUs: "ስለኛ",
    TrackSYM: "TRACK SYM",
    WhoWeAre: "እኛ ማን ነን",
    YourData: "የእርስዎ መረጃ",
    CheckOutOurWebsite: "ድረ ገጻችንን ይጎብኙ",
    SignInToYourAccount: "ወደ መለያዎ ይግቡ",
    DoNotHaveAccount: "መለያ የለዎትም? ይመዝገቡ",
    CovidDetail: "ኮ.ቪ.ድ. ዝርዝር",
    CoronaVirusDesease2019: "ኮሮና ቫይረስ ዲዚዝ 2019",
    WhatDoWeKnowSoFar: "እስካሁን ምን ይታወቃል?",
    WhereDidItComeFrom: "ከየት ነው የመጣው?",
    Misconceptions: "የተለመደና የተሳሳተ ግንዛቤ",
    SymptomsOfCOVID19: "የኮቪድ የህመም ምልክቶች",
    MostCommon: "በጣም የተለመዱ",
    HighFever: "ከፍተኛ ትኩሳት",
    DryCough: "ደረቅ ሳል",
    Fatigue: "ፋቲግ፣ ድካም",
    ShortnessOfBreath: "የትንፋሽ እጥረት",
    Myalgia: "Myalgia",
    LessCommon: "ብዙም ያልተለመዱ",
    Headache: "የእራስ ህመም",
    SoreThroat: "የተዘጋ ጉሮሮ",
    Chills: "ብርድ ብርድ ማለት",
    Anosmia: "ማሽተት አለመቻል",
    maybe: "እእ",
    PreventionIsBetterThanCure: "መከላከል ከመድሀኒት ይሻላል!",
    HandWashing: "እጅ መታጠብ",
    SocialDistancing: "የማህበራዊ ርቀት",
    RecommendedMethods: "የሚመከሩ ዘዴዎች",
    RespiratoryHygiene: "የመተንፈሻ አካላት ንፅህና",
    StayInformed: "አዳዲስ መረጃዎችን ይከታተሉ",
    Spread: "ስርጭት",
    HowDoesCoronavirusBecomeContagious: "ኮሮናቫይረስ እንዴት ተላላፊ ነው?",
    MessageFromTrackSym: "ከTrackSym መልእክት",
    MajorConcern: "የየተሳሳተ ግንዛቤ?",
    MySymptoms: "የህመም ምልክትዎ",
    EditYourSymptoms: "የህመም ምልክትዎን ያርትዑ/ ይቀይሩ",
    LoadingYourSymptom: "የህመም ምልክትዎ እየተከፈተ ነው",
    YouHaveNotRegisteredAnySymptom: "ምንም የህመም ምልክት አልመዘገቡም",
    RunnyNose: "ፈሳሽ ንፍጥ",
    Sneezing: "ማስነጠስ",
    Conjunctivitis: "አይን ማቃጠል(መቅላት)",
    Diarrhea: "ተቅማጥ",
    MediumGradeFever: "መካከለኛ ትኩሳት",
    HighGradeFever: "ከፍተኛ ትኩሳት",
    PersistentDryCough: "የማያቋርጥ ደረቅ ሳል",
    DifficultyBreathing: "የመተንፈስ ችግር",
    Pneumonia: "የሳንባ ምች ",
    RepeatedShakingWithChills: "ተደጋጋሚ መንቀጥቀጥ ከብርድ ብርድ ጋር",
    ChangeProfile: "ፕሮፋይል ለውጥ",
    UpdateYourAgeGroup: "የዕድሜ ክልልዎን ያዘምኑ",
    UpdateYourGender: "ጾታዎን ያዘምኑ",
    NewPassword: "አዲስ የይለፍ ቃል",
    PrivacyPolicy: "Privacy Policy/ ፕራይቨሲ/ግላዊነት ፖሊሲ",
    InformationCollectionAndUse: "የመረጃ አሰባሰብ እና አጠቃቀም",
    ServiceProviders: "አገልግሎት ሰጭዎች",
    LogData: "የመረጃ ምዝግብ/ማስታወሻ",
    Security: "ደህንነት",
    LinkToOtherSites: "ወደ ሌሎች ድረ-ገጾች አገናኝ",
    ChildrensPrivacy: "የልጆች ፕራይቨሲ/ግላዊነት",
    ChangesToThisPrivacyPolicy: "በዚህ የግላዊነት ፖሊሲ ላይ የሚደረጉ ለውጦች",
    TermsAndConditions: "ውል እና ሁኔታዎች",
    ChangesToThisTermsAndConditions: "ለውጥ በዚህ ውል እና ሁኔታ",
    ComingSoon: "በቅርብ ቀን!!",
    Heat: "Heat",
    Regional: "Regional",
    SaveChanges: "Save Changes",
    Done: "Done",
    PleaseTryAgain: "Please try again!",
    YouHaveEnteredWrongUsernameOrPasswordPleaseTryAgain:
      "You have entered wrong username or password, Please try again",
    SigninValidationText:
      "You have entered wrong username or password, Please try again",
    Dismiss: "Dismiss",
    UsernameAlreadyExists: "Username already exists!",
    PrivacyPolicyShortText:
      "By creating an account, I agree to the Track Sym Terms of Use and Privacy Policy",
    PassWordIsRequired: "Password is required",
    PasswordDoesNotMatch: "Password doesn't match",
    PleaseEnterYourUsername: "Please enter your username!",
    UsernameIsRequired: "User name is required",
    PleaseEnterYourPassword: "Please enter your password!",
    PasswordDoNotMatch: "Password Don't match",
    WrongCurrentPassword: "Wrong current password!",
    Required: "required",
    CurrentPassword: "CURRENT PASSWORD",
    ConfirmNewPassword: "CONFIRM NEW PASSWORD",
    ConfirmNewPassword: "Confirm New Password",
    YouHaveSuccessfullyChangedYourPassword:
      "You have successfully changed your password",
    YouHaveSuccessfullyChangedYourProfile:
      "You have successfully changed your profile",
    Default: "Default",
    PasswordCanNotBeEmpty: "Password cannot be empty",
    Cancel: "CANCEL",
    Ok: "OK",
    ConnectionProblem: "Connection Problem",
    CouldNotConnectToServer: "Couldn't connect to server",
    PleaseCheckYourConnection: "Check your internet connection and try again!",
    AgreeingTermsAndServiceOnSignUp:
      "By creating an account, I agree to the Track Sym Terms of\nUse and Privacy Policy",
    CantConnectDueToConnection:
      "Oops, looks like we have connection problem, please try again!",
    PleaseSelectGender: "Please select your gender",
    PleaseSelectAgeGroup: "Please select your age group",
    LoadingGraphDescription: "Loading graph description",
    LoadingCriteriaDescription: "Loading criteria description",
    Languages: "ቋንቋዎች",
    English: "English",
    Amharic: "አማርኛ",
    Oromiffa: "ኦሮምኛ",
    Turkish: "Turkish",
  },
  tr: {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
    Refresh: "Yenile",
    DailyStats: "Günlük İstatistikler",
    TotalStats: "Toplam İstatistikler",
    DailyStatsGraph: "Günlük İstatistik Grafiği",
    TotalStatsGraph: "Toplam İstatistik Grafiği",
    DailyRatesGraph: "Günlük Oran Grafiği",
    NewConfirmed: "Yeni Vaka",
    NewRecovered: "Yeni İyileşen",
    NewDeath: "Yeni Vefat",
    TotalConfirmed: "Toplam Vaka",
    TotalRecovered: "Toplam İyileşen",
    TotalDeath: "Toplam Vefat",
    StartDate: "Başlangıç Tarihi",
    EndDate: "Bitiş Tarihi",
    Confirmed: "Vaka",
    Recovered: "İyileşen",
    Death: "Vefat",
    Deaths: "Ölümler",
    TestCounts: "Test Sayısı",
    ConfirmedRate: "Vaka Oranı",
    RecoveryRate: "İyileşen Oranı",
    DeathRate: "Vefat Oranı ",
    Heat: "YOĞUNLUK",
    Regional: "BÖLGE",
    SearchCity: "Şehir Ara",
    GEO: "GEO",
    GeneralInfo: "Genel Bilgi",
    DemoGraphics: "Demo Grafikler",
    Close: "Kapat",
    TopNews: "En Çok Okunan Haberler",
    GoToNews: "HABERLERE GİT",
    NewsDetail: "Haber Detayı",
    AboutUs: "Hakkımızda",
    TrackSYM: "TRACK SYM",
    WhoWeAre: "BİZ KİMİZ",
    YourData: "VERİLERİNİZ",
    CheckOutOurWebsite: "WEBSİTEMİZİ ZİYARET EDİN",
    SignInToYourAccount: "Hesabınıza Giriş Yapın",
    DoNotHaveAccount: "Hesabınız Yok Mu? Kayıt Olun",
    CovidDetail: "COVID DETAY",
    CoronaVirusDesease2019: "CORONAVİRUS HASTALIĞI 2019",
    WhatDoWeKnowSoFar: "NE BİLİYORUZ ?",
    WhereDidItComeFrom: "NEREDEN GELDİ ?",
    Misconceptions: "YANLIŞ ANLAŞILMALAR",
    SymptomsOfCOVID19: "COVID-19 SEMPTOMLARI",
    MostCommon: "EN YAYGIN",
    HighFever: "Yüksek Ateş",
    DryCough: "Kuru Öksürük",
    Fatigue: "Bitkinlik",
    ShortnessOfBreath: "Nefes Darlığı",
    Myalgia: "Kas Ağrısı",
    LessCommon: "AZ YAYGIN",
    Headache: "Bağ Ağrısı",
    SoreThroat: "Boğaz Ağrısı",
    Chills: "Titreme",
    Anosmia: "Koku Alamama",
    PreventionIsBetterThanCure: "KORUNMA TEDAVİDEN DAHA İYİDİR!",
    HandWashing: "El Yıkama",
    SocialDistancing: "Sosyal Mesafe",
    RecommendedMethods: "ÖNERİLEN YÖNTEMLER",
    RespiratoryHygiene: "Solunum Hijyeni",
    StayInformed: "Haberdar Olun",
    Spread: "YAYILMA",
    HowDoesCoronavirusBecomeContagious: "Corona virüsü nasıl bulaşıcı olur?",
    MessageFromTrackSym: "TrackSym Mesajı",
    MajorConcern: "BÜYÜK ENDİŞE",
    MySymptoms: "Semptomlarım",
    EditYourSymptoms: "Semptomlarını Düzenle",
    LoadingYourSymptom: "Semptomlarınız Yükleniyor",
    YouHaveNotRegisteredAnySymptom: "Herhangi bir belirti kaydetmediniz",
    RunnyNose: "Burun Akıntısı",
    Sneezing: "Hapşırma",
    Conjunctivitis: "Konjonktiv İltihabı",
    Diarrhea: "İshal",
    MediumGradeFever: "Orta Dereceli Ateş",
    HighGradeFever: "Yüksek Ateş",
    PersistentDryCough: "Kalıcı Kuru Öksürük",
    DifficultyBreathing: "Nefes Darlığı",
    Pneumonia: "Akciğer İltihaplanması",
    RepeatedShakingWithChills: "Sürekli Titreme",
    ChangeProfile: "PROFİLİ DEĞİŞTİR",
    UpdateYourAgeGroup: "Yaş grubunu güncelle",
    UpdateYourGender: "Cinsiyeti güncelle",
    NewPassword: "YENİ PAROLA",
    PrivacyPolicy: "Gizlilik Politikası",
    InformationCollectionAndUse: "Bilgi Toplama ve Kullanma",
    ServiceProviders: "Servis Sağlayıcılar",
    LogData: "Verileri Tutma",
    Security: "Güvenlik",
    LinkToOtherSites: "Diğer Sitelere Bağlantı",
    ChildrensPrivacy: "Çocukların Gizliliği",
    ChangesToThisPrivacyPolicy: "Bu Gizlilik Politikasındaki Değişiklikler",
    TermsAndConditions: "Şartlar ve Koşullar",
    ChangesToThisTermsAndConditions: "Bu Hüküm ve Koşulların Şartları",
    ComingSoon: "Yakında!!",
    Heat: "Heat",
    Regional: "Regional",
    SaveChanges: "Save Changes",
    PleaseTryAgain: "Please try again!",
    YouHaveEnteredWrongUsernameOrPasswordPleaseTryAgain:
      "You have entered wrong username or password, Please try again",
    SigninValidationText:
      "You have entered wrong username or password, Please try again",
    Dismiss: "Dismiss",
    UsernameAlreadyExists: "Username already exists!",
    PrivacyPolicyShortText:
      "By creating an account, I agree to the Track Sym Terms of Use and Privacy Policy",
    PassWordIsRequired: "Password is required",
    PasswordDoesNotMatch: "Password doesn't match",
    PleaseEnterYourUsername: "Please enter your username!",
    UsernameIsRequired: "User name is required",
    PleaseEnterYourPassword: "Please enter your password!",
    PasswordDoNotMatch: "Password Don't match",
    WrongCurrentPassword: "Wrong current password!",
    Required: "required",
    CurrentPassword: "CURRENT PASSWORD",
    ConfirmNewPassword: "CONFIRM NEW PASSWORD",
    ConfirmNewPassword: "Confirm New Password",
    YouHaveSuccessfullyChangedYourPassword:
      "You have successfully changed your password",
    YouHaveSuccessfullyChangedYourProfile:
      "You have successfully changed your profile",
    Default: "Default",
    PasswordCanNotBeEmpty: "Password cannot be empty",
    Cancel: "CANCEL",
    Ok: "OK",
    ConnectionProblem: "Connection Problem",
    CouldNotConnectToServer: "Couldn't connect to server",
    Done: "Done",
    PleaseCheckYourConnection: "Check your internet connection and try again!",
    AgreeingTermsAndServiceOnSignUp:
      "By creating an account, I agree to the Track Sym Terms of\nUse and Privacy Policy",
    CantConnectDueToConnection:
      "Oops, looks like we have connection problem, please try again!",
    PleaseSelectGender: "Please select your gender",
    PleaseSelectAgeGroup: "Please select your age group",
    LoadingGraphDescription: "Loading graph description",
    LoadingCriteriaDescription: "Loading criteria description",
    Languages: "Languages",
    English: "English",
    Amharic: "Amharic",
    Oromiffa: "Oromiffa",
    Turkish: "Turkish",
  },
  orm: {
    Information: "Information",
    Data: "Data",
    Map: "Map",
    Symptoms: "My Symptoms",
    Home: "Home",
    News: "News",
    Ethiopia: "Ethiopia",
    About: "About",
    Settings: "Settings",
    EditProfile: "Edit Profile",
    ChangePassword: "Change Password",
    TermsAndPrivacy: "Terms & Privacy",
    DarkMode: "Dark Mode",
    LightMode: "Light Mode",
    LogOut: "Log Out",
    Search: "Search..",
    Welcome: "Welcome",
    Username: "User Name",
    Password: "Password",
    SignIn: "Sign in",
    SignUp: "Sign up",
    AgeGroup: "Age Group",
    Male: "Male",
    Female: "Female",
    Gender: "Gender",
    ConfirmPassword: "Confirm Password",
    ReadMore: "Read More",
    WhatIsCOVID19: "WHAT IS COVID-19 ?",
    COVID19Symptoms: "SYMPTOMS",
    Prevention: "PREVENTION",
    HowDoesItSpreads: "HOW DOES IT SPREAD ?",
    MessageFromUs: "MESSAGE FROM US",
    Refresh: "Haaromsi",
    DailyStats: "Istaatistiksii Guyyuu",
    TotalStats: "Istaatistiksii Waliigalaa",
    DailyStatsGraph: "Gabatee Istaatistiksii Guyyuu",
    TotalStatsGraph: "Gabatee Istaatistiksii Waliigalaa",
    DailyRatesGraph: "Gabatee Jijjiirama Guyyuu",
    NewConfirmed: "Haaraa Kan Qabaman",
    NewRecovered: "Haaraa Kan Dandamatan",
    NewDeath: "Haaraa Kan Du’an",
    TotalConfirmed: "Waliigala Kan Qabaman",
    TotalRecovered: "Waliigala Kan Dandamatan",
    TotalDeath: "Waliigala Kan Du’an",
    StartDate: "Jalqaba Guyyaa",
    EndDate: "Xumura Guyyaa",
    Confirmed: "Kan Qabaman",
    Recovered: "Kan Dandamatan",
    Death: "Du’a",
    Deaths: "Kan Du’an",
    TestCounts: "Baay’ina Waliigalaa",
    ConfirmedRate: "Hammamtaa Namoota Qabamanii",
    RecoveryRate: "Hammamtaa Dandamannaa",
    DeathRate: "Hammamtaa Du’aa",
    Heat: "Ho’a",
    Regional: "Naannoodhaan",
    SearchCity: "Magaalaa Barbaadi",
    GEO: "GEO",
    GeneralInfo: "Odeeffannoo Waliigalaa",
    DemoGraphics: "Demo Graphics",
    Close: "Cufi",
    TopNews: "Oduu Ijoo",
    GoToNews: "Gara Oduu Deemi",
    NewsDetail: "Oduu Gadi-fageenyaan",
    AboutUs: "Waa’ee Keenya",
    TrackSYM: "TRACK SYM",
    WhoWeAre: "NUTI EENYU",
    YourData: "DAATAA KEESSAN",
    CheckOutOurWebsite: "MARSARIITII KEENYA DAAWWADHAA",
    SignInToYourAccount: "Seeni",
    DoNotHaveAccount: "Hin Galmoofnee? Galmaa’aa",
    CovidDetail: "Waa’ee COVID-19 Gadi-fageenyaan",
    CoronaVirusDesease2019: "Dhukkuba Vaayirasii Koronaa 2019",
    WhatDoWeKnowSoFar: "Amma Yoonaatti Maal Beekna?",
    WhereDidItComeFrom: "Eessaa Dhufe?",
    Misconceptions: "Odeeffannoo Dogoggoraa",
    SymptomsOfCOVID19: "MALLATTOOLEE VAAYIRASII KORONAA",
    MostCommon: "MOST COMMON",
    HighFever: "Ho’ina Qaamaa Olaanaa",
    DryCough: "Qufaa Gogaa",
    Fatigue: "Dadhabbii",
    ShortnessOfBreath: "Hafuura Baafachuu Rakkachuu",
    Myalgia: "Myalgia",
    LessCommon: "LESS COMMON",
    Headache: "Mataa Dhukkubbii",
    SoreThroat: "Sore Throat",
    Chills: "Qorrisiisuu / Dhaamochiisuu",
    Anosmia: "Dandeettii Foolii Fuudhuu Dadhabuu",
    PreventionIsBetterThanCure: "OFIRRAA ITTISUUN OF WAL’AANUU IIRRA WAYYA!",
    HandWashing: "Harka Dhiqannaa",
    SocialDistancing: "Walirraa Fageenya Qaamaa",
    RecommendedMethods: "RECOMMENDED METHODS",
    RespiratoryHygiene: "Respiratory Hygiene",
    StayInformed: "Odeeffannoolee Haaraa Ba’an Hordofaa",
    Spread: "TAMSA’INA",
    HowDoesCoronavirusBecomeContagious:
      "How does coronavirus become contagious ?",
    MessageFromTrackSym: "Ergaa TrackSym Irraa",
    MajorConcern: "MAJOR CONCERN",
    MySymptoms: "Mallattoolee Ani Agarsiisu",
    EditYourSymptoms: "Mallattoolee Agarsiistu Gulaali",
    LoadingYourSymptom: "Mallattoolee Galmeessiste Fidaa Jira",
    YouHaveNotRegisteredAnySymptom: "Mallattoo Galmeessiste Hin Qabdu",
    RunnyNose: "Dhangalaa’aa Funyaan Keessaa Yaa’u",
    Sneezing: "Haxxiffannaa",
    Conjunctivitis: "Conjunctivitis",
    Diarrhea: "Garaa Kaasaa",
    MediumGradeFever: "Ho’ina Qaamaa Giddu-galeessa",
    HighGradeFever: "Ho’ina Qaamaa Olaanaa",
    PersistentDryCough: "Qufaa Gogaa addaan hin cinne",
    DifficultyBreathing: "Harganuu Dadhabuu",
    Pneumonia: "Pneumonia",
    RepeatedShakingWithChills: "Hoollannaa fi Dhaamocha addaan hin cinne",
    ChangeProfile: "CHANGE PROFILE",
    UpdateYourAgeGroup: "Update your age group",
    UpdateYourGender: "Update your gender",
    NewPassword: "NEW PASSWORD",
    PrivacyPolicy: "Privacy Policy / Imaammata Dhuunfaa",
    InformationCollectionAndUse: "Information Collection and Use",
    ServiceProviders: "Tajaajila Kan Kennan",
    LogData: "Log Data",
    Security: "Security",
    LinkToOtherSites: "Gara Marsariitii biroo deemuuf",
    ChildrensPrivacy: "Imaammata Dhuunfaa Ijoolleef",
    ChangesToThisPrivacyPolicy: "Changes to This Privacy Policy",
    TermsAndConditions: "Terms & Conditions",
    ChangesToThisTermsAndConditions: "Terms to This Terms and Conditions",
    ComingSoon: "Yeroo Dhiyootti Nu Eegaa!!",
    Heat: "Heat",
    Regional: "Regional",
    SaveChanges: "Save Changes",
    Done: "Done",
    PleaseTryAgain: "Please try again!",
    YouHaveEnteredWrongUsernameOrPasswordPleaseTryAgain:
      "You have entered wrong username or password, Please try again",
    SigninValidationText:
      "You have entered wrong username or password, Please try again",
    Dismiss: "Dismiss",
    UsernameAlreadyExists: "Username already exists!",
    PrivacyPolicyShortText:
      "By creating an account, I agree to the Track Sym Terms of Use and Privacy Policy",
    PassWordIsRequired: "Password is required",
    PasswordDoesNotMatch: "Password doesn't match",
    PleaseEnterYourUsername: "Please enter your username!",
    UsernameIsRequired: "User name is required",
    PleaseEnterYourPassword: "Please enter your password!",
    PasswordDoNotMatch: "Password Don't match",
    WrongCurrentPassword: "Wrong current password!",
    Required: "required",
    CurrentPassword: "CURRENT PASSWORD",
    ConfirmNewPassword: "CONFIRM NEW PASSWORD",
    ConfirmNewPassword: "Confirm New Password",
    YouHaveSuccessfullyChangedYourPassword:
      "You have successfully changed your password",
    YouHaveSuccessfullyChangedYourProfile:
      "You have successfully changed your profile",
    Default: "Default",
    PasswordCanNotBeEmpty: "Password cannot be empty",
    Cancel: "CANCEL",
    Ok: "OK",
    ConnectionProblem: "Connection Problem",
    CouldNotConnectToServer: "Couldn't connect to server",
    Done: "Done",
    PleaseCheckYourConnection: "Check your internet connection and try again!",
    AgreeingTermsAndServiceOnSignUp:
      "By creating an account, I agree to the Track Sym Terms of\nUse and Privacy Policy",
    CantConnectDueToConnection:
      "Oops, looks like we have connection problem, please try again!",
    PleaseSelectGender: "Please select your gender",
    PleaseSelectAgeGroup: "Please select your age group",
    LoadingGraphDescription: "Loading graph description",
    LoadingCriteriaDescription: "Loading criteria description",
    Languages: "Languages",
    English: "English",
    Amharic: "Amharic",
    Oromiffa: "Oromiffa",
    Turkish: "Turkish",
  },
});
