import Vue from "vue";
import Vuex from "vuex";
import graphs from "./graphs";
import heatmap from "./heatmap";
import covidStates from "./covid-states";
import news from "./news";
import loaders from "./loaders";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    allCountries: [
      "World",
      "United States",
      "Spain",
      "Italy",
      "United Kingdom",
      "Germany",
      "France",
      "Russia",
      "Turkey",
      "Iran",
      "Brazil",
      "China",
      "Canada",
      "Belgium",
      "Peru",
      "Netherlands",
      "India",
      "Switzerland",
      "Ecuador",
      "Portugal",
      "Saudi Arabia",
      "Sweden",
      "Ireland",
      "Mexico",
      "Pakistan",
      "Singapore",
      "Chile",
      "Israel",
      "Belarus",
      "Austria",
      "Japan",
      "Qatar",
      "United Arab Emirates",
      "Poland",
      "Romania",
      "Ukraine",
      "South Korea",
      "Indonesia",
      "Denmark",
      "Serbia",
      "Philippines",
      "Bangladesh",
      "Norway",
      "Czech Republic",
      "Dominican Republic",
      "Colombia",
      "Australia",
      "Panama",
      "Malaysia",
      "South Africa",
      "Egypt",
      "Finland",
      "Morocco",
      "Argentina",
      "Kuwait",
      "Algeria",
      "Moldova",
      "Luxembourg",
      "Kazakhstan",
      "Bahrain",
      "Thailand",
      "Hungary",
      "Greece",
      "Afghanistan",
      "Oman",
      "Armenia",
      "Nigeria",
      "Iraq",
      "Uzbekistan",
      "Croatia",
      "Ghana",
      "Azerbaijan",
      "Cameroon",
      "Iceland",
      "Bosnia & Herzegovina",
      "Estonia",
      "Bulgaria",
      "Puerto Rico",
      "Cuba",
      "Guinea",
      "North Macedonia",
      "Slovenia",
      "Slovakia",
      "Lithuania",
      "Ivory Coast",
      "Bolivia",
      "New Zealand",
      "USS Theodore Roosevelt",
      "Djibouti",
      "Charles de Gaulle",
      "Hong Kong",
      "Senegal",
      "Tunisia",
      "Honduras",
      "Latvia",
      "Cyprus",
      "Kosovo",
      "Albania",
      "Kyrgyzstan",
      "Andorra",
      "Lebanon",
      "Niger",
      "Costa Rica",
      "Diamond Princess",
      "Sri Lanka",
      "Burkina Faso",
      "Uruguay",
      "Guatemala",
      "Somalia",
      "Georgia",
      "San Marino",
      "DR Congo",
      "Sudan",
      "Palestine",
      "Mali",
      "Maldives",
      "Tanzania",
      "Malta",
      "Jordan",
      "El Salvador",
      "Jamaica",
      "Taiwan",
      "Kenya",
      "Venezuela",
      "Paraguay",
      "Mauritius",
      "Montenegro",
      "Isle of Man",
      "Equatorial Guinea",
      "Jersey",
      "Gabon",
      "Vietnam",
      "Guinea-Bissau",
      "Guernsey",
      "Rwanda",
      "Congo",
      "Faroe Islands",
      "Liberia",
      "Myanmar",
      "Costa Atlantica",
      "Guam",
      "Gibraltar",
      "Brunei",
      "Sierra Leone",
      "Ethiopia",
      "Madagascar",
      "Luhansk PR",
      "Greg Mortimer",
      "Togo",
      "Cambodia",
      "Cape Verde",
      "Trinidad & Tobago",
      "Bermuda",
      "Zambia",
      "Northern Cyprus",
      "Eswatini",
      "Donetsk PR",
      "Aruba",
      "Monaco",
      "Benin",
      "Uganda",
      "Bahamas",
      "Guyana",
      "Liechtenstein",
      "Barbados",
      "Haiti",
      "Mozambique",
      "USS Kidd",
      "Sint Maarten",
      "Cayman Islands",
      "Chad",
      "Central African Republic",
      "U.S. Virgin Islands",
      "Libya",
      "Nepal",
      "French Polynesia",
      "Macau",
      "South Sudan",
      "Syria",
      "Zimbabwe",
      "Eritrea",
      "Mongolia",
      "Malawi",
      "Tajikistan",
      "Angola",
      "Antigua & Barbuda",
      "East Timor",
      "Botswana",
      "Grenada",
      "Laos",
      "Belize",
      "Fiji",
      "New Caledonia",
      "Saint Lucia",
      "Curaçao",
      "Dominica",
      "Namibia",
      "Saint Vincent",
      "São Tomé & Príncipe",
      "Saint Kitts & Nevis",
      "Nicaragua",
      "Northern Mariana Islands",
      "Falkland Islands",
      "MS Zaandam",
      "Coral Princess",
      "The Gambia",
      "Turks & Caicos Islands",
      "Burundi",
      "Greenland",
      "Montserrat",
      "Seychelles",
      "Vatican City",
      "Suriname",
      "HNLMS Dolfijn",
      "Mauritania",
      "Papua New Guinea",
      "Artsakh",
      "Bhutan",
      "Yemen",
      "British Virgin Islands",
      "Somaliland",
      "Abkhazia",
      "Anguilla",
      "Bonaire",
      "Saba",
      "Sint Eustatius",
      "Comoros",
      "Saint Pierre & Miquelon"
    ]
  },
  getters: {
    getAllCountries(state) {
      return state.allCountries;
    }
  },
  mutations: {},
  actions: {},
  modules: {
    graphs,
    heatmap,
    covidStates,
    news,
    loaders
  }
});
