<template>
  <div class="loadingio-spinner-pulse-3vq0zu7oxj9">
    <div class="ldio-ayp7h880t27">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-ayp7h880t27-1 {
  0% {
    top: 5px;
    height: 90px;
  }
  50% {
    top: 25px;
    height: 50px;
  }
  100% {
    top: 25px;
    height: 50px;
  }
}
@keyframes ldio-ayp7h880t27-2 {
  0% {
    top: 10px;
    height: 80px;
  }
  50% {
    top: 25px;
    height: 50px;
  }
  100% {
    top: 25px;
    height: 50px;
  }
}
@keyframes ldio-ayp7h880t27-3 {
  0% {
    top: 15px;
    height: 70px;
  }
  50% {
    top: 25px;
    height: 50px;
  }
  100% {
    top: 25px;
    height: 50px;
  }
}
.ldio-ayp7h880t27 div {
  position: absolute;
  width: 15px;
}
.ldio-ayp7h880t27 div:nth-child(1) {
  left: 17.5px;
  background: #44d3e6;
  animation: ldio-ayp7h880t27-1 1.5873015873015872s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: -0.3174603174603175s;
}
.ldio-ayp7h880t27 div:nth-child(2) {
  left: 42.5px;
  background: #dbe775;
  animation: ldio-ayp7h880t27-2 1.5873015873015872s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: -0.15873015873015875s;
}
.ldio-ayp7h880t27 div:nth-child(3) {
  left: 67.5px;
  background: #f16292;
  animation: ldio-ayp7h880t27-3 1.5873015873015872s cubic-bezier(0, 0.5, 0.5, 1)
    infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-3vq0zu7oxj9 {
  width: 68px;
  height: 68px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ayp7h880t27 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.68);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ayp7h880t27 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
